name: Publish docker image
on:
    push:
        branches: [ master ]
jobs:
    push_to_registry:

        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        name: Publish docker image
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to Docker
                uses: docker/login-action@v3
                with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ghcr.io/${{ github.repository_owner }}/esa-horaro-proxy:latest
                    cache-from: type=gha
                    cache-to: type=gha
